services:
  webapp:
    container_name: webapp
    build:
      context: .
      dockerfile: Dockerfile-webapp
    ports:
      - "9000:9000"
    volumes:
      - .:/app  # Enables live reloading
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development  # Enables development mode
      - FLASK_DEBUG=1  # Explicitly enables debug mode
      - FLASK_RUN_PORT=9000  # Ensure Flask runs on port 9000
    command: flask run --host=0.0.0.0 --port=9000
